### PR TITLE
Add tests for updated image_molecules

### PR DESCRIPTION
**Pull request by jchodera**
This provides some minimal tests for `image_molecules` in different modes.

There are some clunky aspects to the interface for `anchor_molecules` that could be improved (as the tests illustrate):
- Specifying atom sets instead of actual molecules requires some extra clunky code to expand molecules into atom indices
- It should be straightforward to infer `other_molecules` if the user does not specify these.

### CODE REVIEW

**Comment by mpharrigan** [comment]
> Specifying atom sets instead of actual molecules requires some extra clunky code to expand molecules into atom indices

That's true. Many (?) other api's accept `atom_indices`, which is what I was going for here. 

> It should be straightforward to infer other_molecules if the user does not specify these.

This is true as well :)

Do you want to make either/both of those changes?

**Comment by jchodera** [comment]
> Do you want to make either/both of those changes?

Happy to. Do you want to continue accepting atom indices as well as molecules for flexibility (`anchor_indices`, `anchor_molecules`), or just one or the other type?

**Comment by mpharrigan** [comment]
> Do you want to continue accepting atom indices as well as molecules for flexibility (anchor_indices, anchor_molecules), or just one or the other type?

I'd like to accept one or the other but not both. _However_, I would like the return value(s) of `guess_anchor_molecules` to be passed directly into this function. I think this is just a matter of moving the "index expansion code" from `guess_anchor_molecules` into `image_molecules`

**Comment by jchodera** [comment]
Sounds good. Will add.

**Comment by jchodera** [comment]
This is untested, but along the lines of what I was thinking.

**Comment by jchodera** [comment]
Hm, testing doesn't seem to be enabled here for some reason.

**Comment by jchodera** [comment]
Thanks! Tests passed locally, but I admit it isn't "thoroughly tested".

**Comment by mpharrigan** [comment]
They'll run in the actual mdtraj pull request :)

**Pull request merged**
